##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.4

# Theme tone
dark: false #true/false

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Copyright
copyright: 
  enable: true #display article copyright information, true/false.
  describe: #copyright description

# MathJax Support
mathjax:
  enable: false  #true/false.
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

#Cmments
comment:
  gitalk:
    enable: false ## If you want to use Gitment comment system please set the value to true.
    owner: ## Your GitHub ID, e.g. username
    repo: ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
    client_id: ## GitHub client ID, e.g. 75752dafe7907a897619
    client_secret: ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
    admin: ## Github repo owner and collaborators, only these guys can initialize github issues.
    language: zh-CN ## Language
    pagerDirection: last # Comment sorting direction, available values are last and first.
  duoshuo: ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  uyan: ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
show_archive_count: true ## If you want to show the count of archives in the sidebar widget please set the value to true.
show_archive_type: yearly ## defalut monthly
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.

# Links widget. Empty links will hide widget.
links:
  - title: site-name1
    url: http://www.example1.com/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/
